# use version 3 of the docker compose syntax
version: '3'
services:

  # we named our main service 'web' which runs the nodejs app
  web:
    image: "node:10"
    user: "node"
    environment:
      NODE_ENV: development
    working_dir: /home/node/app
    volumes:
    - ./:/home/node/app
    command: "npm start"
    # first load the 'db' service
    depends_on:
    - db
    # make 'db' a known service/host inside of 'web'
    # use this to make a mysql connection to host 'db'
    links:
    - db
    ports:
    - 3001:8080

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc334sdf
      MYSQL_DATABASE: db_csvdata
      MYSQL_USER: u_csvdata
      MYSQL_PASSWORD: a6YjqN38keo0!h

    volumes:
    - dbdata:/var/lib/mysql
    # map host port 13306 to container port 3306
    ports:
    - 13306:3306
    - 23306:33060

volumes:
  dbdata: